# Generated by Django 5.0.6 on 2024-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
